# Generated by Django 2.2.5 on 2019-09-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='trace_length',
            field=models.FloatField(default=0.0),
        ),
    ]
