# Generated by Django 2.2.5 on 2019-09-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190914_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.TimeField(),
        ),
    ]
