# Generated by Django 2.2.5 on 2019-09-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190914_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creator',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='creator',
            new_name='id_user',
        ),
    ]
