# Generated by Django 2.2.5 on 2019-09-14 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190914_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Car'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_scooter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Scooter'),
        ),
    ]
