# Generated by Django 2.2.5 on 2019-09-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190914_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_amount_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
