# Generated by Django 2.2.5 on 2019-09-15 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190914_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id_car',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id_scooter',
        ),
        migrations.AddField(
            model_name='car',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scooter',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scooter',
            name='opinion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
